### ISSUE TITLE
2.1.0 dist folder doesn't contain updated code

### ISSUE THREAD

**Issue by South-Paw** [badgateway/oauth2-client#98]
👋 

Looks like the dist js files in 2.1.0 don't contain the latest changes

![image](https://user-images.githubusercontent.com/2154764/233879818-3d7abad6-ccbc-48d6-ae89-f22539c6fae9.png)

Odd, because the .d.ts does have correct types.

![image](https://user-images.githubusercontent.com/2154764/233879857-9d29702b-b8b4-4995-a3a1-a204dfc108a4.png)

Side note: have you considered publishing via GitHub actions so the build+publish is handled consistently rather than manually publishing? I'm happy to offer a PR for that if you'd like.

Thanks

**Comment by evert** [comment]
ugh, i don't know why this keeps happening. Something is weird. I have a github action for publishing but it's erroring. Ill take a look at this and re-release.

**Comment by South-Paw** [comment]
No worries, it happens!

here's a copy of an action I use to publish to NPM - it creates the publish every time you create a GitHub release with the format of `*.*.*` (e.g. `2.1.0` - note that it uses the version in the package json though)

```yaml
name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
```
